apiVersion: v1
kind: Service
metadata:
  name: ekart-ssvc
  namespace: webapps
spec:
  type: NodePort
  selector:
    app: ekart
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
      nodePort: 31000
